before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: SjlRyrWAiprWR8u5bg8XnELeMY9MEQiLsROXEaPhru9zMP8PEe345tUGT2xSabPcL+acmIsUbx6HlqhtaPdVElVV9W8WsdTQSmmIoJkxO1UjjZOzfZJA7UXICOh9K2PGDN6B7zGYkr4UEyfM2IGCc3g0tky2hflk96p8CjjmZxw8Eum1O5gVcrcLZm5D4VAWqDFFesaIIHXnTrNsd0/enUhJg9QzHuU6O8EDsnByc28Mzfa+G/pfVyZiWO4zwxjEZz2H98SMIt0vCHMn1EaH+k0zrqnEvl3XsAndiuzOMtf91MZ2lojg4hhkUSZ5FRZdeudfOMzazTJex2dSVA0UcnIwoeF2Yce/NoOc0OJOBClUo+Hjz27Ngy3LHH08jnFXvnsNRO1pVPf+vowJIn9LNXPm8Ah+VJ92aJSsd7FMfFbDsoi7R8/Lg0uTz7hU6ncYXqHJ8ltvj18Mh6rjq4ADjciUZMVq51w9oWH3f3rEQpm3KgcF89ccwTZPKED/QEMZnjZa9oZHWixRJxrXCthvo+9NNq5uB5zufY/7YAbftpDrdZ8o5F9rvShg5fCIJk7fyQsfJPyfnC9oDP4k/7WBGplzk1Dke19hu6tiaLdw0oxC66gQ4cFAwbIFUukIus5/BZ7FH7xOuvKTd7O9eCOLeMJ7XFVcDLiO5mwuRALSwWk= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml
    # - CRYPTO_AES_ENCRYPTED_SH: YjZiMmIwNjYyY2E0OGI5YjQ4ZmI3YTdkYmU4NjViN2I=I93wn43H8K4/eB5Wvi6A2irUFGh17rfCMer38OP/nGwK/4CqVaqXLLQlnG0aW/B+Zt+rUVfwxFxQplOTNqrK3WtMKw1307LZjVv/TPshn/uGxPUqpJTI075x+/b73WEYCXFvwCMwE1GVNiZTS8hGRmmhdLsFy7jlqQwGm0sp7VhUDRSmPsSH5rPplwKCvisqfcMBfCiGjfpXmrbX3gAnwDorfdHLKPFJlzUTcxPeEAjhT8pDckamS+V5scyCZwCqQdRFGOGva3KDyjBIOISbKkdhk1Yn8PczsJe7zrT+j2+mbBV32HPOQdmrwfPC/u3uLZSeTa+kob416KrOdHZWzk1p8DitQBgZUDwBd3ZVvxwc1lOrpciCunR3HXuaJIXKEkrzDu0V2uV/0V9vkeKFmFrTTnKad/4HPtB3GEfBkDPWEWOoYglEeIhMv5cBWdYnfFaV5Kkp145NI8IBQovJ07UyMk7uPcUEcY+V4s3RP3JZ2ZkfSOBXSMT5oa6m6DOX+w3ZNMsj4S0DYt/ncKvOOtqNOiXCChFGgwVd3hgfifgpiWF9CyqDL9AUkRgJyE9uFWccdPID8hw9hvHm1CinboH0CQZkX0/RbIy/R0S8nVS22HTX0SOgq6/yhacalRn6pkX1KxWgZc8gmgTlGvX/YcEzB31sQhy//jm69dd+XELcijk+jFmdf9jnW9Lyo366sRXXdnqFE5gDE4ZMOvyDyURDtKyBnaoy4FnMJY0HAfAIY46MN2/9ZKb9FQTigvVV # CRYPTO_AES_ENCRYPTED_SH
language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
